"""
Turns a set of written doc files into a real GitHub PR: branch off the
pushed commit, commit the doc changes, push the branch, open a PR. Nothing
ever gets pushed to the repo's default branch directly — same
review-friendly pattern as the PR review agent, so generated docs always
go through a human review step before landing on main.
"""
import requests

from app.workers.git_ops import run_git


def checkout_new_branch(local_repo_path: str, branch_name: str, base_sha: str) -> None:
    """Checks out base_sha detached, then creates a new branch from it.
    Must run BEFORE anything writes into the working tree — once doc files
    are written to local_repo_path, this checkout will fail if it would
    overwrite those uncommitted files (see SyncRun failures like #3)."""
    run_git("checkout", base_sha, cwd=local_repo_path)
    run_git("checkout", "-b", branch_name, cwd=local_repo_path)


def commit_changes(local_repo_path: str, relative_paths: list[str], commit_message: str) -> None:
    """Stages the given files and commits. Assumes checkout_new_branch already ran."""
    run_git("add", *relative_paths, cwd=local_repo_path)
    run_git("commit", "-m", commit_message, cwd=local_repo_path)


def push_branch(local_repo_path: str, repo_full_name: str, branch_name: str, github_token: str) -> None:
    """Pushes the branch using a token-authenticated URL, rather than
    relying on any locally configured git credentials — this runs on a
    server/worker, not a developer's machine, so it can't assume SSH keys
    or a stored credential helper are set up."""
    auth_url = f"https://x-access-token:{github_token}@github.com/{repo_full_name}.git"
    run_git("push", auth_url, branch_name, cwd=local_repo_path)


def open_pull_request(
    repo_full_name: str,
    branch_name: str,
    base_branch: str,
    title: str,
    body: str,
    github_token: str,
) -> str:
    """Opens a PR via the GitHub REST API and returns its URL."""
    response = requests.post(
        f"https://api.github.com/repos/{repo_full_name}/pulls",
        headers={
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github+json",
        },
        json={"title": title, "head": branch_name, "base": base_branch, "body": body},
        timeout=30,
    )
    response.raise_for_status()
    return response.json()["html_url"]


def write_back_docs(
    local_repo_path: str,
    repo_full_name: str,
    base_branch: str,
    branch_name: str,
    base_sha: str,
    relative_paths: list[str],
    symbols_changed: int,
    github_token: str,
) -> str:
    """Commits already-written doc files on the already-checked-out branch,
    pushes, and opens a PR. Returns the PR URL."""
    commit_message = f"docs: sync generated documentation for {symbols_changed} symbol(s)"

    commit_changes(local_repo_path, relative_paths, commit_message)
    push_branch(local_repo_path, repo_full_name, branch_name, github_token)

    return open_pull_request(
        repo_full_name=repo_full_name,
        branch_name=branch_name,
        base_branch=base_branch,
        title=f"Sync generated docs for {symbols_changed} changed symbol(s)",
        body=(
            "Auto-generated by the Documentation Generator & Sync Agent.\n\n"
            f"This PR updates documentation for {symbols_changed} symbol(s) whose "
            f"signatures changed in commit `{base_sha}`. Please review before merging."
        ),
        github_token=github_token,
    )